### ISSUE TITLE
Adding addtional return fields

### ISSUE THREAD

**Issue by aram535** [imperva/domain-directory-controller#7]
Our AD uses a custom attribute to denote the lifecycle of the employee.  Is there a way to add custom field to the request so that the custom field is returned?

**Comment by gabibeyo** [comment]
Hope I understand your question.

as you can see from the documentation [documentation](https://github.com/imperva/domain-directory-controller#fieldtype), field can be free strings for both requests and response.
Where ever you see FieldType enum you can instead use your custom String.

Let me know if I answered your question.

**Comment by aram535** [comment]
Yes I did see that and that is what I tried, but the field kept coming back empty - figured I was doing something wrong there.  Figured out the bug in my debug, thank you for your reply.

**Comment by aram535** [comment]
Let me ask a follow up question, and please let me know if you like this in a new issue. I'm now trying to filter on the extra field so that I don't have to get extra entries but looks like the pattern doesn't match the factory.

        Sentence sentence = queryAssembler.addPhrase(FieldType.EMAIL, PhraseOperator.CONTAINS, "email")
                                          .addPhrase(FieldType.DEPARTMENT, PhraseOperator.EQUAL, "IT")
                                          .closeSentence(SentenceOperator.AND);

Works, however: 

        Sentence sentence = queryAssembler.addPhrase(FieldType.EMAIL, PhraseOperator.CONTAINS, "email")
                                          .addPhrase("someotherField", PhraseOperator.EQUAL, "foo")
                                          .closeSentence(SentenceOperator.AND);

Causes a compile error Description

The method addPhrase(FieldType, PhraseOperator, String) in the type QueryAssembler is not applicable for the arguments (String, PhraseOperator, String)

**Comment by gabibeyo** [comment]
I can see that, I will look into that and update you asap. 
We will probably need to release a fixed version.

I will keep you updated.

**Comment by gabibeyo** [comment]
@aram535 , I think I fixed that, also tested it in my environment.
The changes are committed in this branch (still not in master):
https://github.com/imperva/domain-directory-controller/tree/enable_query_by_fieldtype_string

Can you please clone this branch, compile and test it in your environment?
The version I used for this branch is 7.3.3.0.1.0, so you can point to it in your project.

**Comment by aram535** [comment]
Yes the query looks like exactly what I needed: 
`'(&(&(objectCategory=person)(objectClass=user))(identitylifecyclestate=*active*)(mail=*fname.lname@company.com*))'`

**Comment by gabibeyo** [comment]
Perfect. I will release an official version in the next weeks.
Meanwhile you can work with this one. Let me know if you have any other questions.

**Comment by davidkhanpk** [comment]
I am trying to get name of the group. I tried every field type and common strings related to name but I can't get the name of the group.

`queryRequestGroup.setObjectType(ObjectType.GROUP);
queryRequestGroup.addRequestedField(FieldType.EMAIL);`

I can get the email but unable to get the group name.

**Comment by gabibeyo** [comment]
Hi @davidkhanpk ,

Try:
queryRequestGroup.addRequestedField(FieldType.COMMON_NAME);
OR
queryRequestGroup.addRequestedField("displayName");

Please let me know...
