### ISSUE TITLE
Remove Member From Group

### ISSUE THREAD

**Issue by wbautistaEXPEDIA** [imperva/domain-directory-controller#8]
What is the expected approach to removing a user from a group? Currently, the `ChangeRequest#remove` method does not accept a field value. Ideally, we would use that method and provide the value we want to remove. For instance, a group has multiple `member` fields. I do not want to remove ALL `member`s, just a specific one.

**Comment by gabibeyo** [comment]
Did you try this one? You can specify the DN of the Member to remove

----------
`
RemoveRequest removeRequest = new RemoveRequest("<The Distinguished Name of the AD object to remove>");
removeRequest.setEndpoint(endpoint);

try (Connector connector = new Connector(removeRequest)) {
    connector.executeRemoveRequest();
}
`

**Comment by wbautistaEXPEDIA** [comment]
Won't that remove the user object completely from AD? I just want to remove the user from a group, not all of AD.

**Comment by gabibeyo** [comment]
Yes, you are right. Now I understand what you ate trying to do.
Currently what I would do (probably not the best way in hearth ):
- fetch the list of members of the group
- remove in-memory the one you want to remove
- perform a  remove request via ddc to all the 'member' fields
- create a change request via ddc to re-add the new edited list without the un wanted member

Again, not the best way but it should work. What do you think?

**Comment by wbautistaEXPEDIA** [comment]
That sounds a bit risky. Turns out, the underlying framework supports already supports this. I've opened a PR to expose this functionality.

**Comment by gabibeyo** [comment]
@wbautistaEXPEDIA , Thanks! I reviewed and merged the PR.
A new version will be released in the next couple of days.

Thanks!
